"""nama perubahan

Revision ID: 61d311ed2710
Revises: 
Create Date: 2026-05-17 08:28:40.732822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61d311ed2710'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('_alembic_tmp_survey')
    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.drop_column('require_email')

    with op.batch_alter_table('survey_response', schema=None) as batch_op:
        batch_op.alter_column('survey_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=150),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_response', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('survey_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.add_column(sa.Column('require_email', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True))

    op.create_table('_alembic_tmp_survey',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('email_required', sa.BOOLEAN(), nullable=True),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('start_date', sa.VARCHAR(length=20), nullable=True),
    sa.Column('end_date', sa.VARCHAR(length=20), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.VARCHAR(length=30), nullable=True),
    sa.Column('questions', sa.TEXT(), nullable=True),
    sa.Column('unsur_responden', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('notification')
    # ### end Alembic commands ###
